name: Mysql actions demo
run-name: ${{ github.actor }} is testing out Mysql GitHub Actions 🚀

on: [push]

jobs:
  setup_mysql_database:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: Secret5555
          MYSQL_DATABASE: usersdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Wait for MySQL to be ready
        run: sleep 15

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Deploy schema to MySQL
        run: mysql -h 127.0.0.1 -u root -pSecret5555 usersdb < schema_changes.sql
